learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns= [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world', 'number':'100'}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="nav-brand" href="{% url 'index' %}">BRAND</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
              <li><a class="nav-link" href="{% url 'basic_app:other' %}">Other</a></li>
              <li><a class="nav-link" href="{% url 'basic_app:relative' %}" >Relative</a></li>
            </ul>
        </div>
      </nav>

      <div class="container">

        {% block body_block %}
        <!-- anythin outside of thing will be inherited if tou extend -->
        {% endblock %}

      </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
      <h1>WELCOME TO INDEX PAGE</h1>
      <h1>{{text|cut:'hello'}}</h1>
      <h1>{{number|add:"99"}}</h1>
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
        <h1>WELCOME TO THE OTHER PAGE</h1>
  {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
      <h1>WELCOME TO RELATIVE TEMPLATES</h1>
  {% endblock %}